apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-ingress
spec:
  ingressClassName: haproxy
  rules:
  -  http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spring-boot-3-rest-api-example-master
            port:
              number: 80
   
   