##Define a Role:
##his role will define the permissions within the sonarqube namespace.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: backstage
  name: backstage-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

##Create a RoleBinding:
##This role binding will assign the role to a user, group, or service account.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backstage-rolebinding
  namespace: backstage
subjects:
- kind: User
  name: "srikar.k@kshema.co" #Replace with the actual user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: backstage-role
  apiGroup: rbac.authorization.k8s.io