apiVersion: apps/v1
kind: Deployment
metadata:
  name: endorsment
spec:
  minReadySeconds: 20
  replicas: 3
  selector:
    matchLabels:
      app: test01
  strategy:
    rollingUpdate:
      maxSurge: 25
      maxUnavailable: 25
    type: RollingUpdate
  template:
    metadata:
      name: tepmlatetest01
      labels:
        app: test01
    spec:
      containers:
        - image: kshemapoc.azurecr.io/{{REPO01}}:{{TAG01}}
          name: test01
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "400m"
              memory: "300Mi"
            limits:
              cpu: "600m"
              memory: "500Mi"
          # livenessProbe:
          #   httpGet:
          #     path: /endorsement/actuator/health/liveness
          #     port: 8080
          #   initialDelaySeconds: 15
          #   periodSeconds: 10
      imagePullSecrets:
        - name: mykshema-poc2
---
apiVersion: v1
kind: Service
metadata:
  name: endorsment
spec:
  selector:
    app: test01
  ports:
    - name: appport
      port: 80
      targetPort: 8080